### ISSUE TITLE
 [Process] kill() returned unexpected error 1

### ISSUE THREAD

**Issue by a123478we** [AAChartModel/AAChartKit#794]
图形加载过程中  控制台打印出  [Process] kill() returned unexpected error 1

这是什么意思？

**Comment by AAChartModel** [comment]
* question:  

Why I get the console warning: [Process] kill() returned unexpected error 1 when I load a WKWebView in iOS13.2?

* answer: 

It's a bug in WebKit (or the underlying OS itself). And no, it was not fixed in 13.2 release.

https://stackoverflow.com/questions/58321114/why-i-get-the-console-warning-process-kill-returned-unexpected-error-1-when

**Comment by AAChartModel** [comment]
这似乎是系统的 bug,恐怕有点为难(摊手)
